---
output: 
  github_document:
    html_preview: false
# params: 
#   actor_id: "esch" 
#   data_date: "2020-03-26"
#   sha: "sha"
---

# Planting Shade

## Introduction 

Trees provide critical ecosystem services and are important components of both natural and built environments. With a desire to create healthy places for people to live (mitigate heat islands and/or reduce home cooling costs, reduce localized flooding risk, improve mental health, etc.) and a resilient future (carbon sequestration, biodiversity, etc.), building or enhancing tree canopy cover is something we care about. However, knowing where opportunities lie to build or enhance tree canopy cover is a real challenge. 

<br>
There are many dimensions that can and should be considered when deciding where to plant trees.

- **Existing tree cover**: knowing which areas have relatively low tree cover versus areas that have relatively high tree cover can help direct tree planting efforts. 
- **Equity**: communities of color and other marginalized groups disproportionately live in areas which lack tree cover and/or have high negative externalities which could be mitigated in part by tree cover (air pollution, etc.)
- **Existing land use**: information about land use can help direct messaging and outreach (ie if opportunities exist for planting trees within residential area, the messaging will look very different than if the greatest opportunities for planting trees lies within commercial zoned areas)
- Other: ...

<br>
This data was aggregated to help facilitate discussions around enhancing our region's tree canopy in order to improve climate resilience, livability, and beauty. Of course, important pieces are missing, not fully unpacked, and/or tied together in incomplete ways. For instance, there are practical limitations on data availability/vintage/accuracy/spatial resolution. There are also limitations on which parts of the discussion data can contribute to ("yes" to identifying ares which might be suitable for tree planting, "no" (at the moment) to knowing which tree species might be most suitable for the location).

<br>
This is a quick and dirty test to see if this works. And/or if it would be useful to jump start future conversations. If this seems like a useful approach, let's think more critically about everything.

<br>

## Methods

Pulling together:

- "Greenness" (normalized difference vegetation index (NDVI) from Sentinel-2, peak NDVI in 2020 aggregated to the block group level and also at 10x10m resolution)
- Equity considerations data
- Existing land use

<hr>
